Add ability to get it working with proxy
8398a7/action-slack pull request #144
Opened 2021-06-11 22:38 UTC by sethumadhav07

currently slack connection using webhook is not working with proxy which is a common requirement in many corporate settings.
Code change in this PR addresses that.

Reference: Proxy requests with a custom agent
https://www.npmjs.com/package/@slack/webhook

2021-06-18 08:32 UTC, sethumadhav07 commented
@8398a7 can you please take a look at this PR?

2021-07-23 20:02 UTC, 8398a7 commented
@sethumadhav07 Sorry for the late confirmation.
CI doesn't seem to work for some reason. Will you push it again?

2021-07-28 19:27 UTC, sethumadhav07 commented
@8398a7 can you please take a look at it and approve?

2021-08-15 11:41 UTC, 8398a7 requested changes

2021-08-15 11:41 UTC, 8398a7 commented on dist/index.js
> +(()=>{var __webpack_modules__={7716:e=>{"use strict";e.exports=JSON.parse('{"name":"@slack/webhook","version":"6.0.0","description":"Official library for using the Slack Platform\'s Incoming Webhooks
Do not commit this file.

2021-08-16 23:20 UTC, sethumadhav07 commented on dist/index.js
> +(()=>{var __webpack_modules__={7716:e=>{"use strict";e.exports=JSON.parse('{"name":"@slack/webhook","version":"6.0.0","description":"Official library for using the Slack Platform\'s Incoming Webhooks
addressed please take a look

2021-08-31 11:11 UTC, 8398a7 commented
CI is failing due to reduced test coverage. Can you please fix it?

2021-09-21 04:15 UTC, sethumadhav07 commented
I fixed the code coverage for tests. can you please a look at it and approve?

2021-09-21 04:22 UTC, 8398a7 approved these changes

2021-09-21 04:23 UTC, merged

2021-09-21 04:32 UTC, sethumadhav07 commented
will a new release/tag be created?

2021-09-21 05:19 UTC, sethumadhav07 commented
@8398a7  can a new release/tag be created?