Add field 'pullRequest' as pull request title, number with link
8398a7/action-slack pull request #164
Opened 2021-10-21 23:07 UTC by nowsprinting

Add field `pullRequest` as pull request title, number with link.

Motivation:
When triggered with pull request event, the commit is the SHA of the merge commit, and the message is "HEAD into BASE".
I can trace the pull request page from `job` or `workflow`, but it would be nice to be able to refer to the pull request directly.

Note:
When it is triggered by push event, this field shows "n/a".

~~Discussions:
Which is the best format for the pullRequest field?
Current: `<url | title #numer>`
Alternative: `title <html_url | #numer>`~~

2021-11-08 23:50 UTC, nowsprinting commented
Thanks!

> I prefer `<url | title #numer>`.

It's the current format.

2021-11-11 06:44 UTC, 8398a7 requested changes
Sorry, I forgot to submit review.

2021-11-11 11:52 UTC, nowsprinting commented on docs/content/fields.md
> +| pullRequest | `AS_PULL_REQUEST`       | Pull Request title, number with link                        |
Fixed in 83b844f

2021-11-12 13:32 UTC, 8398a7 approved these changes

2021-11-12 13:32 UTC, merged

2021-11-12 13:32 UTC, 8398a7 commented
thanks!